apiVersion: v1
kind: ServiceAccount
metadata:
  name: pod-lookup
  namespace: k8s-api-demo
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: pod-lookup
  namespace: k8s-api-demo
rules:
  - verbs:
      - get
      - watch
      - list
    apiGroups:
      - ''
    resources:
      - pods
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: pod-lookup
  namespace: k8s-api-demo
subjects:
  - kind: ServiceAccount
    name: pod-lookup
    namespace: k8s-api-demo
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: pod-lookup